name: layout
description: >-
  Sample app from "Building Layouts", https://docs.flutter.dev/ui/layout.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  example_utils:
    path: ../flutter/website/examples/example_utils
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: [images/]
